ionic plugin add cordova-plugin-camera
ionic plugin add cordova-plugin-compat
ionic plugin add cordova-plugin-console
ionic plugin add cordova-plugin-device
ionic plugin add cordova-plugin-file
ionic plugin add cordova-plugin-filepath
ionic plugin add cordova-plugin-file-transfer
ionic plugin add cordova-plugin-splashscreen
ionic plugin add cordova-plugin-statusbar
ionic plugin add cordova-plugin-whitelist
ionic plugin add cordova-sqlite-storage
ionic plugin add ionic-plugin-keyboard
ionic plugin add phonegap-plugin-barcodescanner
ionic plugin add https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin.git
ionic plugin add cordova-plugin-network-information
ionic platform remove android
ionic platform add android
