/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'saudeuser' at '04/07/16 12:29' with Gradle 2.9
 *
 * @author saudeuser, @date 04/07/16 12:29
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
